"""add user discriminator column

Revision ID: 05f4f2e1029e
Revises: b3670ac16e43
Create Date: 2023-04-12 03:53:00.703862

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "05f4f2e1029e"
down_revision = "b3670ac16e43"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("discriminator", sa.SmallInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "discriminator")
    # ### end Alembic commands ###
