"""add user table

Revision ID: 57ad979c6250
Revises: 9382aebc9f9b
Create Date: 2023-04-11 19:13:24.952653

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "57ad979c6250"
down_revision = "9382aebc9f9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=True),
        sa.Column("avatar_hash", sa.Text(), nullable=True),
        sa.Column("guild_avatar_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("in_guild", sa.Boolean(), nullable=True),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("staff", sa.Boolean(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
