"""add cascading deletions

Revision ID: 5f5a229a98ca
Revises: ed33989b1790
Create Date: 2023-05-19 03:31:14.126925

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f5a229a98ca"
down_revision = "ed33989b1790"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_messages_channels_id_channel", "messages", type_="foreignkey"
    )
    op.drop_constraint("fk_messages_users_id_author", "messages", type_="foreignkey")
    op.drop_constraint("fk_messages_threads_id_thread", "messages", type_="foreignkey")
    op.create_foreign_key(
        "fk_messages_users_id_author",
        "messages",
        "users",
        ["author"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_messages_threads_id_thread",
        "messages",
        "threads",
        ["thread"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_messages_channels_id_channel",
        "messages",
        "channels",
        ["channel"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_reactions_users_id_user", "reactions", type_="foreignkey")
    op.create_foreign_key(
        "fk_reactions_users_id_user",
        "reactions",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_reactions_users_id_user", "reactions", type_="foreignkey")
    op.create_foreign_key(
        "fk_reactions_users_id_user", "reactions", "users", ["user"], ["id"]
    )
    op.drop_constraint(
        "fk_messages_channels_id_channel", "messages", type_="foreignkey"
    )
    op.drop_constraint("fk_messages_threads_id_thread", "messages", type_="foreignkey")
    op.drop_constraint("fk_messages_users_id_author", "messages", type_="foreignkey")
    op.create_foreign_key(
        "fk_messages_threads_id_thread", "messages", "threads", ["thread"], ["id"]
    )
    op.create_foreign_key(
        "fk_messages_users_id_author", "messages", "users", ["author"], ["id"]
    )
    op.create_foreign_key(
        "fk_messages_channels_id_channel", "messages", "channels", ["channel"], ["id"]
    )
    # ### end Alembic commands ###
