"""add thread table

Revision ID: 9382aebc9f9b
Revises: 33acd613eb6a
Create Date: 2023-04-11 19:12:33.458541

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9382aebc9f9b"
down_revision = "33acd613eb6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("auto_archive_duration", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("threads")
    # ### end Alembic commands ###
