"""remove user staff column

Revision ID: b3670ac16e43
Revises: 83f1945c25f2
Create Date: 2023-04-12 03:11:44.593947

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b3670ac16e43"
down_revision = "83f1945c25f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "staff")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("staff", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
