"""add reaction table

Revision ID: ed33989b1790
Revises: 05f4f2e1029e
Create Date: 2023-05-19 02:45:19.520657

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed33989b1790"
down_revision = "05f4f2e1029e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.Column("message", sa.BigInteger(), nullable=True),
        sa.Column("user", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message"],
            ["messages.id"],
            name="fk_reactions_messages_id_message",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], name="fk_reactions_users_id_user"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reactions")
    # ### end Alembic commands ###
